### ISSUE TITLE
Program freezes when I change active window to game

### ISSUE THREAD

**Issue by kevalalajnen** [thetarkus/WebMCam#12]
I wanted to use WebMCam in order to record short videos of machines I built in the game Besiege, however, when I'm finished recording something and try to stop the program I can't click anything, so it will keep recording forever. I have to stop the program from the task bar or it won't stop.

**Comment by 1Seann** [comment]
This but with any game, once it freezes, if you press spacebar it will create a Microsoft .NET Framework error.
![capture](https://cloud.githubusercontent.com/assets/7369730/6768763/8f56d744-d0ce-11e4-84a5-0a316b1080ae.PNG)
The details then contain this: https://gist.github.com/1Seann/6df05bdecf3cfe861d50

**Comment by thetarkus** [comment]
WebMCam doesn't really do so well on recording massive frames with it's current image capture method, so while it may look like it's freezing it's actually trying to throw those frames into it's temp folder and playing catch-up. I'll look into this today and see if I can get a DirectX capture thing going.

@1Seann and you're just out of RAM or actual hard disk storage

**Comment by jserodio** [comment]
so? when will this be fixed?

**Comment by thetarkus** [comment]
The image capture method is fast enough for lots of frames. It's more dependent on your storage medium. Recording massive resolution shots and high FPS means it needs to save quicker and quicker which your computer may not be able to do.

With the release of WebMCam v2.0, I'm hoping this has been fixed. Please see if this fixes your problem. If your problem still occurs, feel free to open a new issue.
