### ISSUE TITLE
Application Freezes when recording with audio

### ISSUE THREAD

**Issue by ScriptKi77y** [thetarkus/WebMCam#15]
There seems to be some conflict going on with Adobe photoshop CS6 and attempting to record it.

Creating a text area, then right clicking the layer and opening the blending properties window immediately causes WebMCam to stop responding to any sort of user input unless I immediately change the windows theme 2 or 3 times oddly enough..

Edit: this post was wrong

**Comment by ScriptKi77y** [comment]
ok, so I did a few more tests. It's not just with CS6, it does this frequently when recording anything it seems. but only when I am recording something with sound. I have to manually terminate the process because it stops taking screen shots and continues recording sound indefinitely

**Comment by thetarkus** [comment]
When I have free time I'm going to use a different audio capture method. As for the changing the windows theme thing, for me sometimes the titlebar clicks through; if that's what you're talking about then under the control buttons (Iconify, Maximize, Close) you can drag from there.

Also make sure you're not running out of memory!

**Comment by ScriptKi77y** [comment]
I'm on windows 7 x64 sp1 i5 4690 with 8gb. I've been using it a lot to quickly record things in my browser, programming stuff.. It's really quite useful but it will always freezes right at around 20 seconds in and I have to close it with taskmanager. by that time it's using over 1g with constant 20% cpu. the application window doesn't focus. The program always has more than enough memory available when this happens.

**Comment by thetarkus** [comment]
I've finally made free time to work on WebMCam. Hopefully it's not too late.
Test with WebMCam v2.0. Be sure not to record with too high of a framerate if your shot's resolution is going to be massive.

Thanks!
