### ISSUE TITLE
Unresponsive window when the resolution is too big

### ISSUE THREAD

**Issue by wog24435** [thetarkus/WebMCam#16]
For small resolution webms, the program works great, but when you want to record a big portion of your screen, it simply ignores your actions after you start recording.
In the following video, from second 26 onwards I'm trying to stop recording, but nothing happens. I try clicking on all the buttons and options but nothing. I have tried alt tabbing, but it didn't work. The only way to stop the program is by killing it through the task manager.
http://a.pomf.se/kofptc.mp4

I'm using Windows 8.1 64 bit.

**Comment by githuis** [comment]
Having the exact same issue.

**Comment by thetarkus** [comment]
Unfortunately, the capturing process requires lots of power as it's just taking many many, many screenshots. It will never be able to make huge videos, not with the current (inefficient) method. I should add a warning when the window is resized too large.

**Comment by wog24435** [comment]
Thank you. That will certainly be helpful.
