### ISSUE TITLE
Record area around moving cursor

### ISSUE THREAD

**Issue by mote0230** [thetarkus/WebMCam#18]
It would be neat if there was an option to keep the cursor centered in the recording area and have it automatically follow the cursor.

**Comment by thetarkus** [comment]
This sounds like a great feature. When I get some free time I will implement this, unless someone else wants to submit a pull request before I do.

**Comment by Nhowka** [comment]
I've sent a pull request with that feature.

**Comment by mote0230** [comment]
Can you also make a new release with this please? :)
