### ISSUE TITLE
Example README link doesn't display on Chorme

### ISSUE THREAD

**Issue by Ralph-Wiggum** [thetarkus/WebMCam#21]
Hi I was looking at your README and my browser wouldn't display your example. I'm running Google Chrome Version 47.0.2526.106 m and get the following console log error:

example.webm:1 Refused to load media from 'https://raw.githubusercontent.com/TheTarkus/WebMCam/master/Preview/example.webm' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'media-src' was not explicitly set, so 'default-src' is used as a fallback.

**Comment by thetarkus** [comment]
I'm not sure that this has anything to do with my data. I think this is GitHub's problem. Try a different browser is the only thing I could recommend.
