### ISSUE TITLE
Freezes during recording regardless of settings (audio, cursor, framerate)

### ISSUE THREAD

**Issue by TheDevo** [thetarkus/WebMCam#22]
I've tried installing various different versions of the .NET framework, didn't help.
The seconds counter in the window title carries on, but the buttons on the UI of WebmCam freeze, can't close the application from the "X" in the window, only via the taskbar or taskmanager.

**Comment by thetarkus** [comment]
Almost 2 months later I finally have found the time to work on WebMCam. Hopefully it is not too late!
With the release of version 2.0, I'm hoping will have fixed your problem?
