### ISSUE TITLE
Processing error with system language settings using comma for floating point numbers

### ISSUE THREAD

**Issue by FuzzyGS** [thetarkus/WebMCam#26]
Processing window won't process the video if used on a system that has language settings using commas for floating point numbers.

Easy fix would be in "**FormProcess.cs**":
Add: 
Line5:

> using System.Globalization;

Change:
Line 35-36 to:
```
                .Replace("{fps}", fps.ToString(CultureInfo.InvariantCulture))
                .Replace("{avg:fps}", avg.ToString(CultureInfo.InvariantCulture))
```

alternatively only change:
Line 34-35 to:
```
                .Replace("{fps}", fps.ToString().Replace(',', '.'))
                .Replace("{avg:fps}", avg.ToString().Replace(',', '.'))
```

to make it work.

**Comment by thetarkus** [comment]
If you make a pull request with this update before I do, I'll merge it.
