### ISSUE TITLE
Color artifacts when playing back webms

### ISSUE THREAD

**Issue by Clavus** [thetarkus/WebMCam#29]
Don't know if this is an issue with the WebMCam or the playback applications, but some of the recordings I made have artifacts that look like this:
[http://i.imgur.com/wOJNVME.png](http://i.imgur.com/wOJNVME.png)

.. but only when played back in desktop media players like VLC, Windows Media Player or Media Player Classic (the artifacts are green in the last two). When playing back in a browser (Chrome / Firefox), there are no artifacts.

This doesn't happen with all recordings, some play back just fine in all applications. Can't quite figure out what causes it, but it tends to appear when recording at higher framerates or at higher resolutions with WebMCam. Maybe a codec issue on my end?

**Comment by thetarkus** [comment]
I would say look in the frame viewer after you capture a shot and check for the artifacts in there. If there are no artifacts in the viewer, drag it into VLC/WMP/MPC and see if the artifacts are now there. No artifacts in the viewer means it's either FFmpeg's encoder or the player (it's probably the player).

Personally, on my computer I cannot even play a webm file in VLC and only used a browser to test.

**Comment by Clavus** [comment]
Yeah, I'm thinking it might be something with the K-Lite codec pack that I've got installed. Thanks for the quick response!

**Comment by thetarkus** [comment]
Good luck!
