### ISSUE TITLE
Comment Error

### ISSUE THREAD

**Issue by Seraphli** [theTarkus/WebMCam#31]
Recorder.cs:line 71

// Enable Capture Timer
durationTimerDelegate = new PInvoke.MMTimerProc(DurationTick);
durationTimerId = PInvoke.timeSetEvent(100, 0, durationTimerDelegate, 0, 1);

// Enable Duration Timer
captureTimerDelegate = new PInvoke.MMTimerProc(CaptureTick);
captureTimerId = PInvoke.timeSetEvent((uint)(1000 / fps), 0, captureTimerDelegate, 0, 1);

By the way, thank you for this awesome tool.

**Comment by theTarkus** [comment]
Fixed, thanks!
