### ISSUE TITLE
Recording a certain window instead of screen space

### ISSUE THREAD

**Issue by Gnts** [thetarkus/WebMCam#35]
Title, is it possible?
I couldn't figure it out how. 
For example recording the whole screen in 1080p

I am looking to record 10s length video several times in a row for different visual tests and I want to position every recording test at exactly the same size/position.

Cheers!

**Comment by theTarkus** [comment]
It could be added but you'd have lots of trouble with frame saving with high resolution captures.
OBS [https://obsproject.com] would be more suitable for what you're looking to do, I believe.

**Comment by eettenoiram** [comment]
Hey thetarkus,
a fullscreen option would really be nice. A workaround for too high resolutions could be to reduce screen resolution (i.e. down to 1280x800) but be able to record the whole screen with all menubars etc.

Cheers!
