### ISSUE TITLE
Audio not working

### ISSUE THREAD

**Issue by 3ternal** [theTarkus/WebMCam#37]
I can't seem to get audio recording to work in WebMCam 2.1.0. It was working in an older version (1.5 maybe?).

Here are the properties of a clip I recorded: 
![dypbh7f](https://cloud.githubusercontent.com/assets/4501366/16812607/af006014-48e2-11e6-82d4-6ef878dcfba3.png)

From the looks of it, there's no audio track at all, so the problem isn't with my Windows volume settings. I tried recording a clip from both the Unity game engine and from a regular .mkv movie file. The Capture Audio checkbox was checked, and I have the NAudio.dll file in my folder, so I'm not sure what's missing.

**Comment by theTarkus** [comment]
Post your ffmpeg arguments here

**Comment by 3ternal** [comment]
Sure, here they are:
`-framerate {avg:fps} -i {format} {audio} -c:v libvpx -b:v 2M -r {avg:fps} {output}`

**Comment by theTarkus** [comment]
Try out v2.2.0 [https://github.com/theTarkus/WebMCam/releases/tag/220]
If it doesn't work out of the box, go into options and click the Reset Args button and restart WebMCam and retry.

If that still doesn't work... when the ffmpeg process form shows up after recording, post the first 3 lines right before the hyphen

**Comment by 3ternal** [comment]
After trying again and going through the ffmpeg log, I just got to the bottom of this - it was a problem with my MPC filters. The audio worked fine on VLC, so I updated my LAV Filters and now MPC works as well.

Sorry for the confusion, but I'm glad it's working!

**Comment by theTarkus** [comment]
Ah! Glad you sorted it out!
