### ISSUE TITLE
Saving as .mp4?

### ISSUE THREAD

**Issue by dannyblank** [thetarkus/WebMCam#50]
Hey dude, love the program been using it for a while now.

Slack seems to have added .mp4 integration and I know that on renaming the Webm file extension to .mp4 it still lets the file play correctly.

I was wondering in your next update could you have the option to choose .mp4 from the dropdown when saving?  If I try and save the file out with the extension .mp4 the encoder fails to start correctly.

**Comment by altbdoor** [comment]
Because by default, the encoder used is VPX, which is for WebM You can see it in the options `-c:v libvpx`.

In order to use MP4, you need to change it to `-c:v libx264`, and save your file as `output.mp4` accordingly.

**Comment by thetarkus** [comment]
This and the ability to modify arguments before rendering will be added today.

**Comment by dannyblank** [comment]
Ahh yeah dude, I just tried the latest version. It's great the .gif was also a very welcome awesome addition.
