### ISSUE TITLE
Cannot save output [bug?]

### ISSUE THREAD

**Issue by leamsifigs** [thetarkus/WebMCam#54]
I cannot seem to output any recordings as of late. 
output can be read here: http://pastebin.com/GaSeWA6d
Since it's kind of long.

actions leading up to error:
1. Record like normal
2. delete some of the starting frames
3. delete some of the ending frames
4. cry

Current system:
Dell XPS 13 9343
Win10 64bit
New sadness module installed

**Comment by thetarkus** [comment]
Try opening the options and hitting "Reset Arguments" then Save. Let me know if that fixes it

**Comment by leamsifigs** [comment]
I reset the arguments and it seems to work fine now. Were those additional arguments caused by something I did?

**Comment by thetarkus** [comment]
The updated FFmpeg binary required some new default arguments, so I'm assuming you updated from <2.4.0 which didn't add those args automatically. Nothing you did broke it.
