### ISSUE TITLE
Deleting frames does not work.

### ISSUE THREAD

**Issue by ToppestOfDogs** [thetarkus/WebMCam#55]
I've tried both the delete key and the right click menu, but frames cannot be deleted anymore.
I remember this feature working a few months ago, but I don't know which version that was.
Windows 10 Pro 64bit

**Comment by dannyblank** [comment]
Hey dude, can you add some better repro instructions or a webm/ gif of this. I can't repro on my end using 2.4.0 :/

**Comment by ToppestOfDogs** [comment]
It happens at random, no way to decide if it does or not. Sorry.

**Comment by TimonSpringlab** [comment]
I am also having this issue using 2.4
It looks like it happens when you record with audio
