### ISSUE TITLE
Not working well with Potplayer

### ISSUE THREAD

**Issue by Dozen7** [thetarkus/WebMCam#61]
https://potplayer.daum.net/

I use this player program with WebMCam, 
but it record the different screen and shows WebMCam recorder in recorded frame.

I check the DPI because of previous issues,
It works well with 100% dpi in Windows 10, but not well with 125% dpi.

Check this bug, and hope it fixed. Thank you for making great things.

**Comment by thetarkus** [comment]
This is a DPI issue and not Potplayer.
Commit below should solve the problem.

Commit: https://github.com/thetarkus/WebMCam/commit/3735b0866954bb0745ba1eba2f72c697549bbbf2
